name: Release to npm

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup (Install node & pnpm)
        uses: ./.github/actions/setup

      - name: Build (if needed)
        run: pnpm release
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}